import type { AppRoute } from "./routeTypes";

// ── Public marketing routes ────────────────────────────────────────────────
const PUBLIC_ROUTES: AppRoute[] = [
  {
    id: "home",
    path: "/",
    title: "Home",
    description: "AffectLog open-source trustworthy AI assessment platform",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "product",
    path: "/product",
    title: "Product",
    description: "Platform capabilities overview",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "guided-assessment",
    path: "/guided-assessment",
    title: "Guided Assessment",
    description: "Step-by-step AI assessment wizard with guardrails",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "dataset-audit",
    path: "/dataset-audit",
    title: "Dataset Audit",
    description: "Dataset profiling, PII scanning, xAPI metrics",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "model-assessment",
    path: "/model-assessment",
    title: "Model Assessment",
    description: "ML model adapters, explanations, model cards",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "compliance-exports",
    path: "/compliance-exports",
    title: "Compliance Exports",
    description: "SOPs, data cards, JSON-LD compliance graphs",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "community",
    path: "/community",
    title: "Community Edition",
    description: "Self-hosted open-source core deployment",
    area: "public",
    status: "active",
    requiresAuth: false,
    aliases: ["/open-source", "/community-edition"],
  },
  {
    id: "cloud",
    path: "/cloud",
    title: "Managed Cloud",
    description: "AffectLog-operated managed infrastructure",
    area: "public",
    status: "active",
    requiresAuth: false,
    aliases: ["/cloud-managed", "/managed"],
  },
  {
    id: "pricing",
    path: "/pricing",
    title: "Editions",
    description: "Compare Community and Managed Cloud editions",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "security",
    path: "/security",
    title: "Security",
    description: "RBAC, pseudonymisation, audit logs, disclosure policy",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "developers",
    path: "/developers",
    title: "Developers",
    description: "Developer resources, recipes, model adapters",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "docs",
    path: "/docs",
    title: "Documentation",
    description: "Documentation gateway — guides, API, architecture",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "ecosystem",
    path: "/ecosystem",
    title: "Ecosystem",
    description: "Prometheus-X BB04, EDGE-Skills, data spaces",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "openapi",
    path: "/openapi",
    title: "OpenAPI",
    description: "OpenAPI-first automation workflows and API spec",
    area: "public",
    status: "active",
    requiresAuth: false,
    aliases: ["/api"],
  },
  {
    id: "self-host",
    path: "/self-host",
    title: "Self-host",
    description: "Docker Compose and self-hosted deployment guide",
    area: "public",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "request-access",
    path: "/request-access",
    title: "Request Access",
    description: "Request managed access or get in touch",
    area: "public",
    status: "active",
    requiresAuth: false,
    aliases: ["/contact"],
  },
];

// ── Auth routes ────────────────────────────────────────────────────────────
const AUTH_ROUTES: AppRoute[] = [
  {
    id: "login",
    path: "/login",
    title: "Sign In",
    description: "Sign in to your AffectLog account",
    area: "auth",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "register",
    path: "/register",
    title: "Register",
    description: "Create an AffectLog account",
    area: "auth",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "awaiting-approval",
    path: "/awaiting-approval",
    title: "Awaiting Approval",
    description: "Account pending administrator review",
    area: "auth",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "activate",
    path: "/activate",
    title: "Activate Account",
    description: "Activate your account via email token",
    area: "auth",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "forgot-password",
    path: "/forgot-password",
    title: "Forgot Password",
    description: "Request a password reset",
    area: "auth",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "reset-password",
    path: "/reset-password",
    title: "Reset Password",
    description: "Set a new password via reset token",
    area: "auth",
    status: "active",
    requiresAuth: false,
  },
];

// ── Console routes (community edition: no tenant slug) ─────────────────────
// In managed edition these would be /app/:tenantSlug/...
const CONSOLE_ROUTES: AppRoute[] = [
  {
    id: "console-home",
    path: "/app",
    title: "Dashboard",
    description: "Tenant assessment overview and quick actions",
    area: "console",
    status: "active",
    requiresAuth: true,
  },
  {
    id: "console-wizard",
    path: "/app/wizard",
    title: "Guided Assessment",
    description: "Step-by-step guided AI assessment wizard",
    area: "console",
    status: "active",
    requiresAuth: true,
  },
  {
    id: "console-datasets",
    path: "/app/datasets",
    title: "Datasets",
    description: "Upload, validate, and manage datasets",
    area: "console",
    status: "active",
    requiresAuth: true,
  },
  {
    id: "console-audits",
    path: "/app/audit",
    title: "Audit Runs",
    description: "View completed and in-progress audit runs",
    area: "console",
    status: "active",
    requiresAuth: true,
  },
  {
    id: "console-models",
    path: "/app/models",
    title: "Models",
    description: "Register and manage ML models",
    area: "console",
    status: "active",
    requiresAuth: true,
  },
  {
    id: "console-compliance",
    path: "/app/compliance",
    title: "Compliance",
    description: "Generate and download compliance exports",
    area: "console",
    status: "active",
    requiresAuth: true,
  },
  {
    id: "console-recipes",
    path: "/app/recipes",
    title: "Recipes",
    description: "Reusable assessment pipeline specs",
    area: "console",
    status: "planned",
    requiresAuth: true,
  },
  {
    id: "console-interoperability",
    path: "/app/interoperability",
    title: "Interoperability",
    description: "CARiSMA/LOLA metadata export",
    area: "console",
    status: "planned",
    requiresAuth: true,
  },
  {
    id: "console-developers",
    path: "/app/developers",
    title: "Developer Tools",
    description: "API keys and developer integrations",
    area: "console",
    status: "planned",
    requiresAuth: true,
  },
  {
    id: "console-settings",
    path: "/app/settings",
    title: "Settings",
    description: "Tenant and account settings",
    area: "console",
    status: "planned",
    requiresAuth: true,
  },
];

// ── Admin routes ───────────────────────────────────────────────────────────
const ADMIN_ROUTES: AppRoute[] = [
  {
    id: "admin-home",
    path: "/admin",
    title: "Admin Dashboard",
    description: "Tenant administration overview",
    area: "admin",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["admin"],
  },
  {
    id: "admin-registrations",
    path: "/admin/pending-registrations",
    title: "Pending Registrations",
    description: "Review and approve pending user registrations",
    area: "admin",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["admin"],
  },
  {
    id: "admin-users",
    path: "/admin/users",
    title: "Users",
    description: "Manage tenant users and roles",
    area: "admin",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["admin"],
  },
  {
    id: "admin-audit-log",
    path: "/admin/audit-log",
    title: "Audit Log",
    description: "System and user activity audit log",
    area: "admin",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["admin"],
  },
  {
    id: "admin-email",
    path: "/admin/email",
    title: "Email Settings",
    description: "Configure SMTP and email templates",
    area: "admin",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["admin"],
  },
  {
    id: "admin-system",
    path: "/admin/system",
    title: "System Health",
    description: "Service health and system diagnostics",
    area: "admin",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["admin"],
  },
];

// ── Platform admin routes (managed edition only) ───────────────────────────
const PLATFORM_ROUTES: AppRoute[] = [
  {
    id: "platform-home",
    path: "/platform",
    title: "Platform Dashboard",
    description: "Multi-tenant platform administration overview",
    area: "platform",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["platform_admin"],
    requiredEdition: "managed",
  },
  {
    id: "platform-tenants",
    path: "/platform/tenants",
    title: "Tenants",
    description: "Manage all platform tenants",
    area: "platform",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["platform_admin"],
    requiredEdition: "managed",
  },
  {
    id: "platform-feature-flags",
    path: "/platform/feature-flags",
    title: "Feature Flags",
    description: "Enable and disable platform feature flags",
    area: "platform",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["platform_admin"],
    requiredEdition: "managed",
  },
  {
    id: "platform-usage",
    path: "/platform/usage",
    title: "Platform Usage",
    description: "Aggregate usage metrics across tenants",
    area: "platform",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["platform_admin"],
    requiredEdition: "managed",
  },
  {
    id: "platform-support-access",
    path: "/platform/support-access",
    title: "Support Access",
    description: "Manage support access permissions",
    area: "platform",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["platform_admin"],
    requiredEdition: "managed",
  },
  {
    id: "platform-system-health",
    path: "/platform/system-health",
    title: "System Health",
    description: "Platform-wide system health monitoring",
    area: "platform",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["platform_admin"],
    requiredEdition: "managed",
  },
  {
    id: "platform-audit-log",
    path: "/platform/audit-log",
    title: "Platform Audit Log",
    description: "Platform-level activity and security audit log",
    area: "platform",
    status: "active",
    requiresAuth: true,
    requiredPermissions: ["platform_admin"],
    requiredEdition: "managed",
  },
];

// ── Error routes ───────────────────────────────────────────────────────────
const ERROR_ROUTES: AppRoute[] = [
  {
    id: "not-found",
    path: "/404",
    title: "Page Not Found",
    description: "404 — requested page does not exist",
    area: "error",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "forbidden",
    path: "/403",
    title: "Access Denied",
    description: "403 — you do not have permission to view this page",
    area: "error",
    status: "active",
    requiresAuth: false,
  },
  {
    id: "server-error",
    path: "/500",
    title: "Server Error",
    description: "500 — an unexpected error occurred",
    area: "error",
    status: "active",
    requiresAuth: false,
  },
];

// ── Master registry ────────────────────────────────────────────────────────
export const ALL_ROUTES: AppRoute[] = [
  ...PUBLIC_ROUTES,
  ...AUTH_ROUTES,
  ...CONSOLE_ROUTES,
  ...ADMIN_ROUTES,
  ...PLATFORM_ROUTES,
  ...ERROR_ROUTES,
];

export const ROUTE_BY_ID = Object.fromEntries(ALL_ROUTES.map((r) => [r.id, r]));
export const ROUTE_BY_PATH = Object.fromEntries(ALL_ROUTES.map((r) => [r.path, r]));

/** Resolve a route by id — throws in dev if not found */
export function getRoute(id: string): AppRoute {
  const route = ROUTE_BY_ID[id];
  if (!route) {
    if (import.meta.env.DEV) throw new Error(`[routes] Unknown route id: "${id}"`);
    console.error(`[routes] Unknown route id: "${id}"`);
    return ROUTE_BY_ID["not-found"]!;
  }
  return route;
}

/** All active public routes (for sitemap) */
export const PUBLIC_SITEMAP_ROUTES = PUBLIC_ROUTES.filter((r) => r.status === "active");
