import type { CTA } from "./ctaTypes";

// ── Global header CTAs ─────────────────────────────────────────────────────
const HEADER_CTAS: CTA[] = [
  {
    id: "header-request-access",
    label: "Request Access",
    purpose: "Primary header conversion — request managed cloud access",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_header_request_access",
  },
  {
    id: "header-self-host",
    label: "Self-host",
    purpose: "Secondary header option — deploy community edition",
    targetType: "route",
    targetId: "self-host",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_header_self_host",
  },
  {
    id: "header-sign-in",
    label: "Sign in",
    purpose: "Header auth entry point",
    targetType: "route",
    targetId: "login",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
];

// ── Home page CTAs ─────────────────────────────────────────────────────────
const HOME_CTAS: CTA[] = [
  {
    id: "home-hero-primary",
    label: "Request Managed Access",
    purpose: "Home hero primary — drive managed cloud signups",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_home_hero_primary",
  },
  {
    id: "home-hero-secondary",
    label: "Deploy Community Edition",
    purpose: "Home hero secondary — drive self-host downloads",
    targetType: "route",
    targetId: "self-host",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_home_hero_secondary",
  },
  {
    id: "home-hero-technical",
    label: "Explore Product",
    purpose: "Home hero technical — product overview for evaluators",
    targetType: "route",
    targetId: "product",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "home-mid-cta",
    label: "Run Guided Assessment",
    purpose: "Home mid-page contextual — highlight core workflow",
    targetType: "route",
    targetId: "guided-assessment",
    variant: "secondary",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "home-final-cta",
    label: "Compare Editions",
    purpose: "Home final — drive pricing comparison",
    targetType: "route",
    targetId: "pricing",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
];

// ── Product page CTAs ──────────────────────────────────────────────────────
const PRODUCT_CTAS: CTA[] = [
  {
    id: "product-hero-primary",
    label: "Launch Guided Assessment",
    purpose: "Product hero — route to guided assessment feature",
    targetType: "route",
    targetId: "guided-assessment",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_product_hero_primary",
  },
  {
    id: "product-hero-secondary",
    label: "View Architecture",
    purpose: "Product hero — architecture documentation",
    targetType: "route",
    targetId: "docs",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "product-hero-technical",
    label: "View OpenAPI",
    purpose: "Product hero technical — API spec for developers",
    targetType: "route",
    targetId: "openapi",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "product-final-cta",
    label: "Request Managed Access",
    purpose: "Product final — conversion for evaluated product",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_product_final",
  },
];

// ── Guided Assessment page CTAs ───────────────────────────────────────────
const GUIDED_ASSESSMENT_CTAS: CTA[] = [
  {
    id: "guided-hero-primary-loggedout",
    label: "Start Guided Assessment",
    purpose: "Guided assessment hero — drive registration for new users",
    targetType: "route",
    targetId: "register",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_guided_hero_loggedout",
  },
  {
    id: "guided-hero-primary-loggedin",
    label: "Start Guided Assessment",
    purpose: "Guided assessment hero — launch wizard for logged-in users",
    targetType: "route",
    targetId: "console-wizard",
    variant: "primary",
    area: "console",
    requiredAuth: true,
    trackingEvent: "cta_guided_hero_loggedin",
  },
  {
    id: "guided-hero-secondary",
    label: "See Capability Matrix",
    purpose: "Guided hero secondary — documentation for evaluators",
    targetType: "route",
    targetId: "docs",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "guided-hero-technical",
    label: "Read Guardrails",
    purpose: "Guided hero technical — guardrail rules for developers",
    targetType: "route",
    targetId: "docs",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "guided-final-cta",
    label: "Request Managed Access",
    purpose: "Guided final — conversion for assessed users",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_guided_final",
  },
];

// ── Dataset Audit page CTAs ────────────────────────────────────────────────
const DATASET_AUDIT_CTAS: CTA[] = [
  {
    id: "dataset-hero-primary-loggedout",
    label: "Run Dataset Audit",
    purpose: "Dataset audit hero — drive registration for new users",
    targetType: "route",
    targetId: "register",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_dataset_hero_loggedout",
  },
  {
    id: "dataset-hero-primary-loggedin",
    label: "Run Dataset Audit",
    purpose: "Dataset audit hero — launch wizard for logged-in users",
    targetType: "route",
    targetId: "console-wizard",
    variant: "primary",
    area: "console",
    requiredAuth: true,
    trackingEvent: "cta_dataset_hero_loggedin",
  },
  {
    id: "dataset-hero-secondary",
    label: "View Sample Workflow",
    purpose: "Dataset audit secondary — documentation example",
    targetType: "route",
    targetId: "docs",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "dataset-hero-technical",
    label: "Self-host Demo",
    purpose: "Dataset audit technical — local demo for developers",
    targetType: "route",
    targetId: "self-host",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "dataset-final-cta",
    label: "Deploy Community Edition",
    purpose: "Dataset audit final — drive open-source deployment",
    targetType: "route",
    targetId: "self-host",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_dataset_final",
  },
];

// ── Model Assessment page CTAs ─────────────────────────────────────────────
const MODEL_ASSESSMENT_CTAS: CTA[] = [
  {
    id: "model-hero-primary-loggedout",
    label: "Register a Model",
    purpose: "Model assessment hero — drive registration",
    targetType: "route",
    targetId: "register",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_model_hero_loggedout",
  },
  {
    id: "model-hero-primary-loggedin",
    label: "Register a Model",
    purpose: "Model assessment hero — navigate to models console",
    targetType: "route",
    targetId: "console-models",
    variant: "primary",
    area: "console",
    requiredAuth: true,
    trackingEvent: "cta_model_hero_loggedin",
  },
  {
    id: "model-hero-secondary",
    label: "View Model Adapters",
    purpose: "Model assessment secondary — adapter documentation",
    targetType: "route",
    targetId: "docs",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "model-hero-technical",
    label: "Add an Adapter",
    purpose: "Model assessment technical — contribute a new adapter",
    targetType: "external",
    targetId: "AFFECTLOG_CONTRIBUTING",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "model-final-cta",
    label: "Open Developer Guide",
    purpose: "Model assessment final — route to developer resources",
    targetType: "route",
    targetId: "developers",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_model_final",
  },
];

// ── Compliance Exports page CTAs ───────────────────────────────────────────
const COMPLIANCE_EXPORTS_CTAS: CTA[] = [
  {
    id: "compliance-hero-primary-loggedout",
    label: "Generate Sample JSON-LD",
    purpose: "Compliance exports hero — drive registration",
    targetType: "route",
    targetId: "register",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_compliance_hero_loggedout",
  },
  {
    id: "compliance-hero-primary-loggedin",
    label: "Generate Export",
    purpose: "Compliance exports hero — navigate to compliance console",
    targetType: "route",
    targetId: "console-compliance",
    variant: "primary",
    area: "console",
    requiredAuth: true,
    trackingEvent: "cta_compliance_hero_loggedin",
  },
  {
    id: "compliance-hero-secondary",
    label: "View Export Catalog",
    purpose: "Compliance secondary — documentation catalog",
    targetType: "route",
    targetId: "docs",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "compliance-hero-technical",
    label: "View OpenAPI",
    purpose: "Compliance technical — export API spec",
    targetType: "route",
    targetId: "openapi",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "compliance-final-cta",
    label: "Request Managed Access",
    purpose: "Compliance final — conversion for enterprise compliance use",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_compliance_final",
  },
];

// ── Community page CTAs ────────────────────────────────────────────────────
const COMMUNITY_CTAS: CTA[] = [
  {
    id: "community-hero-primary",
    label: "Deploy Community Edition",
    purpose: "Community hero — drive self-hosted deployment",
    targetType: "route",
    targetId: "self-host",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_community_hero_primary",
  },
  {
    id: "community-hero-secondary",
    label: "View on GitHub",
    purpose: "Community hero secondary — source code",
    targetType: "external",
    targetId: "AFFECTLOG_REPO",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "community-hero-technical",
    label: "Read Contributor Guide",
    purpose: "Community hero technical — contribution documentation",
    targetType: "external",
    targetId: "AFFECTLOG_CONTRIBUTING",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "community-final-cta",
    label: "Start Self-hosting",
    purpose: "Community final — drive deployment action",
    targetType: "route",
    targetId: "self-host",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_community_final",
  },
];

// ── Cloud page CTAs ────────────────────────────────────────────────────────
const CLOUD_CTAS: CTA[] = [
  {
    id: "cloud-hero-primary",
    label: "Request Managed Access",
    purpose: "Cloud hero primary — convert managed cloud interest",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_cloud_hero_primary",
  },
  {
    id: "cloud-hero-secondary",
    label: "Compare Editions",
    purpose: "Cloud hero secondary — pricing comparison",
    targetType: "route",
    targetId: "pricing",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "cloud-hero-technical",
    label: "Read Security Model",
    purpose: "Cloud hero technical — security documentation for evaluators",
    targetType: "route",
    targetId: "security",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "cloud-final-cta",
    label: "Request Managed Access",
    purpose: "Cloud final — final conversion",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_cloud_final",
  },
];

// ── Pricing page CTAs ──────────────────────────────────────────────────────
const PRICING_CTAS: CTA[] = [
  {
    id: "pricing-hero-primary",
    label: "Request Managed Access",
    purpose: "Pricing hero — managed cloud conversion",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_pricing_hero_primary",
  },
  {
    id: "pricing-hero-secondary",
    label: "Deploy Community Edition",
    purpose: "Pricing hero secondary — open-source alternative",
    targetType: "route",
    targetId: "self-host",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "pricing-hero-technical",
    label: "Compare Security",
    purpose: "Pricing hero technical — security comparison for evaluators",
    targetType: "route",
    targetId: "security",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "pricing-final-cta",
    label: "Choose Your Deployment",
    purpose: "Pricing final — guide to deployment decision",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_pricing_final",
  },
];

// ── Security page CTAs ─────────────────────────────────────────────────────
const SECURITY_CTAS: CTA[] = [
  {
    id: "security-hero-primary",
    label: "Request Security Review",
    purpose: "Security hero — drive enterprise security evaluations",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_security_hero_primary",
  },
  {
    id: "security-hero-secondary",
    label: "Read Security Policy",
    purpose: "Security hero secondary — disclosure policy on GitHub",
    targetType: "external",
    targetId: "AFFECTLOG_SECURITY",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "security-hero-technical",
    label: "Review RBAC Model",
    purpose: "Security hero technical — RBAC documentation",
    targetType: "route",
    targetId: "docs",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "security-final-cta",
    label: "Request Managed Access",
    purpose: "Security final — enterprise conversion",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_security_final",
  },
];

// ── Developers page CTAs ───────────────────────────────────────────────────
const DEVELOPERS_CTAS: CTA[] = [
  {
    id: "developers-hero-primary",
    label: "Contribute on GitHub",
    purpose: "Developers hero — drive open-source contributions",
    targetType: "external",
    targetId: "AFFECTLOG_REPO",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_developers_hero_primary",
  },
  {
    id: "developers-hero-secondary",
    label: "Add a Dataset Recipe",
    purpose: "Developers hero secondary — contribution guide for recipes",
    targetType: "external",
    targetId: "AFFECTLOG_CONTRIBUTING",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "developers-hero-technical",
    label: "View OpenAPI",
    purpose: "Developers hero technical — API spec",
    targetType: "route",
    targetId: "openapi",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "developers-final-cta",
    label: "Clone and Run Locally",
    purpose: "Developers final — local development setup",
    targetType: "route",
    targetId: "self-host",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_developers_final",
  },
];

// ── Docs page CTAs ─────────────────────────────────────────────────────────
const DOCS_CTAS: CTA[] = [
  {
    id: "docs-hero-primary",
    label: "Read API Docs",
    purpose: "Docs hero — API reference as primary entry point",
    targetType: "route",
    targetId: "openapi",
    variant: "primary",
    area: "docs",
    requiredAuth: false,
  },
  {
    id: "docs-hero-secondary",
    label: "Start Self-hosting",
    purpose: "Docs hero secondary — local deployment guide",
    targetType: "route",
    targetId: "self-host",
    variant: "outline",
    area: "docs",
    requiredAuth: false,
  },
  {
    id: "docs-hero-technical",
    label: "Open Developer Guide",
    purpose: "Docs hero technical — developer resources",
    targetType: "route",
    targetId: "developers",
    variant: "ghost",
    area: "docs",
    requiredAuth: false,
  },
  {
    id: "docs-final-cta",
    label: "Launch Guided Assessment",
    purpose: "Docs final — guide readers into the product",
    targetType: "route",
    targetId: "guided-assessment",
    variant: "primary",
    area: "docs",
    requiredAuth: false,
  },
];

// ── Ecosystem page CTAs ────────────────────────────────────────────────────
const ECOSYSTEM_CTAS: CTA[] = [
  {
    id: "ecosystem-hero-primary",
    label: "Explore Technical Docs",
    purpose: "Ecosystem hero — route to Prometheus-X BB04 technical docs",
    targetType: "external",
    targetId: "PROMETHEUS_X_TAI_DOCS",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_ecosystem_hero_primary",
  },
  {
    id: "ecosystem-hero-secondary",
    label: "View BB04 Overview",
    purpose: "Ecosystem hero secondary — Prometheus-X BB04 overview",
    targetType: "external",
    targetId: "PROMETHEUS_X_TRUSTWORTHY_AI",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "ecosystem-hero-technical",
    label: "View on GitHub",
    purpose: "Ecosystem hero technical — source code",
    targetType: "external",
    targetId: "AFFECTLOG_REPO",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "ecosystem-final-cta",
    label: "Request Managed Access",
    purpose: "Ecosystem final — convert ecosystem interest to signup",
    targetType: "route",
    targetId: "request-access",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_ecosystem_final",
  },
];

// ── OpenAPI page CTAs ──────────────────────────────────────────────────────
const OPENAPI_CTAS: CTA[] = [
  {
    id: "openapi-hero-secondary",
    label: "Try API Locally",
    purpose: "OpenAPI hero secondary — local setup",
    targetType: "route",
    targetId: "self-host",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "openapi-hero-technical",
    label: "Contribute API Client",
    purpose: "OpenAPI technical — contribute SDK or client library",
    targetType: "external",
    targetId: "AFFECTLOG_CONTRIBUTING",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "openapi-final-cta",
    label: "Build Integration",
    purpose: "OpenAPI final — route to developer resources",
    targetType: "route",
    targetId: "developers",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
];

// ── Self-host page CTAs ────────────────────────────────────────────────────
const SELF_HOST_CTAS: CTA[] = [
  {
    id: "self-host-hero-secondary",
    label: "View on GitHub",
    purpose: "Self-host hero secondary — GitHub repo for cloning",
    targetType: "external",
    targetId: "AFFECTLOG_REPO",
    variant: "outline",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "self-host-hero-technical",
    label: "Read Security Checklist",
    purpose: "Self-host technical — security hardening guide",
    targetType: "route",
    targetId: "security",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "self-host-final-cta",
    label: "Deploy Community Edition",
    purpose: "Self-host final — primary deployment action",
    targetType: "external",
    targetId: "AFFECTLOG_REPO",
    variant: "primary",
    area: "marketing",
    requiredAuth: false,
    trackingEvent: "cta_self_host_final",
  },
];

// ── Request Access form CTAs ───────────────────────────────────────────────
const REQUEST_ACCESS_CTAS: CTA[] = [
  {
    id: "request-access-submit",
    label: "Submit Request",
    purpose: "Request access form submission",
    targetType: "api-action",
    targetId: "submit-access-request",
    variant: "primary",
    area: "auth",
    requiredAuth: false,
    trackingEvent: "cta_request_access_submit",
  },
  {
    id: "request-access-secondary",
    label: "Compare Editions",
    purpose: "Request access — help users understand options before submitting",
    targetType: "route",
    targetId: "pricing",
    variant: "ghost",
    area: "marketing",
    requiredAuth: false,
  },
  {
    id: "request-access-success-home",
    label: "Return Home",
    purpose: "Post-submission — return to homepage after access request",
    targetType: "route",
    targetId: "home",
    variant: "outline",
    area: "auth",
    requiredAuth: false,
  },
];

// ── Console dashboard CTAs ─────────────────────────────────────────────────
const CONSOLE_CTAS: CTA[] = [
  {
    id: "dashboard-run-wizard",
    label: "Run Guided Assessment",
    purpose: "Dashboard primary — start a new assessment run",
    targetType: "route",
    targetId: "console-wizard",
    variant: "primary",
    area: "console",
    requiredAuth: true,
    trackingEvent: "cta_dashboard_run_wizard",
  },
  {
    id: "dashboard-upload-dataset",
    label: "Upload Dataset",
    purpose: "Dashboard secondary — add dataset for analysis",
    targetType: "route",
    targetId: "console-datasets",
    variant: "secondary",
    area: "console",
    requiredAuth: true,
  },
  {
    id: "dashboard-view-audits",
    label: "View Audit Runs",
    purpose: "Dashboard — navigate to audit run history",
    targetType: "route",
    targetId: "console-audits",
    variant: "outline",
    area: "console",
    requiredAuth: true,
  },
  {
    id: "datasets-upload",
    label: "Upload Dataset",
    purpose: "Datasets page primary — ingest a new dataset",
    targetType: "api-action",
    targetId: "upload-dataset",
    variant: "primary",
    area: "console",
    requiredAuth: true,
  },
  {
    id: "datasets-validate",
    label: "Validate Existing Dataset",
    purpose: "Datasets secondary — run validation on an existing dataset",
    targetType: "api-action",
    targetId: "validate-dataset",
    variant: "secondary",
    area: "console",
    requiredAuth: true,
  },
  {
    id: "audits-new-assessment",
    label: "New Guided Assessment",
    purpose: "Audit runs page primary — start a new assessment",
    targetType: "route",
    targetId: "console-wizard",
    variant: "primary",
    area: "console",
    requiredAuth: true,
  },
  {
    id: "models-register",
    label: "Register Model",
    purpose: "Models page primary — register a new ML model",
    targetType: "api-action",
    targetId: "register-model",
    variant: "primary",
    area: "console",
    requiredAuth: true,
  },
  {
    id: "compliance-generate-export",
    label: "Generate Export",
    purpose: "Compliance page primary — generate compliance export from audit",
    targetType: "api-action",
    targetId: "generate-compliance-export",
    variant: "primary",
    area: "console",
    requiredAuth: true,
  },
];

// ── Admin CTAs ─────────────────────────────────────────────────────────────
const ADMIN_CTAS: CTA[] = [
  {
    id: "admin-review-registrations",
    label: "Review Pending Registrations",
    purpose: "Admin registrations primary — review queue",
    targetType: "route",
    targetId: "admin-registrations",
    variant: "primary",
    area: "admin",
    requiredAuth: true,
    requiredPermissions: ["admin"],
  },
  {
    id: "admin-approve-registration",
    label: "Approve",
    purpose: "Approve a pending user registration",
    targetType: "api-action",
    targetId: "approve-registration",
    variant: "success",
    area: "admin",
    requiredAuth: true,
    requiredPermissions: ["admin"],
  },
  {
    id: "admin-reject-registration",
    label: "Reject",
    purpose: "Reject a pending user registration",
    targetType: "api-action",
    targetId: "reject-registration",
    variant: "danger",
    area: "admin",
    requiredAuth: true,
    requiredPermissions: ["admin"],
  },
];

// ── Master registry ────────────────────────────────────────────────────────
const ALL_CTAS: CTA[] = [
  ...HEADER_CTAS,
  ...HOME_CTAS,
  ...PRODUCT_CTAS,
  ...GUIDED_ASSESSMENT_CTAS,
  ...DATASET_AUDIT_CTAS,
  ...MODEL_ASSESSMENT_CTAS,
  ...COMPLIANCE_EXPORTS_CTAS,
  ...COMMUNITY_CTAS,
  ...CLOUD_CTAS,
  ...PRICING_CTAS,
  ...SECURITY_CTAS,
  ...DEVELOPERS_CTAS,
  ...DOCS_CTAS,
  ...ECOSYSTEM_CTAS,
  ...OPENAPI_CTAS,
  ...SELF_HOST_CTAS,
  ...REQUEST_ACCESS_CTAS,
  ...CONSOLE_CTAS,
  ...ADMIN_CTAS,
];

export const CTA_REGISTRY = Object.fromEntries(ALL_CTAS.map((c) => [c.id, c]));
export type CTAId = keyof typeof CTA_REGISTRY;

export function getCTA(id: CTAId): CTA {
  const cta = CTA_REGISTRY[id];
  if (!cta) {
    const msg = `[ctaRegistry] Unknown CTA id: "${id}"`;
    if (import.meta.env.DEV) throw new Error(msg);
    console.error(msg);
  }
  return cta;
}

export { ALL_CTAS };
